# This is a basic workflow to help you get started with Actions

name: docs-update

on:
  push:
    branches: [ main ]

jobs:
  docs-docker:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kbrwn/docs:latest
      credentials:
        username: kbrwn
        password: ${{ secrets.REGISTRY_TOKEN }}
    steps: 
    - run: sh /app/run.sh
    
