# This is a basic workflow to help you get started with Actions

name: docs-update

on:
  push:
    branches: [ main ]

jobs:
  docs-docker:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kubecost/docsbuilder:latest
      env:
          GH_PAT: ${{ secrets.gh_pat }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps: 
    - run: sh run.sh
      working-directory: /app
    
